#!/bin/bash
source buffermaker
## Example of buffermaker tui program

add-mode testui
	:: [left] format-left
	:: [up] format-up
	:: [right] format-right
	:: [down] format-down
	:: RET link-enter
	:: C-c die
	:: "$(kbd k)" previous-line
	:: "$(kbd j)" next-line
	mode-options
		:: else :

declare-buffer counter
bf_d+=(
	[line]=5
	[column]=0
	[info]="Testui"
	[mode]=testui
	[filetype]='format'
	[syntax]=syntax-format
	[syntax-exec]=1
	[render-type]=per-char
)

function inc {
	((incnum++))
	make-render-line 3
	redraw
}

function dec {
	((incnum--))
	make-render-line 3
	redraw
}

function show-more {
	buffer[7]="${buffer[6]}"
	buffer[6]='More: '\
'<o> id: setnum select: set-number redraw right: obj menu left: : up: show-less down: show-less '\
'text: <f> link Set number </f> '\
'</o> '\
'<o> id: menu select: menu zero right: obj close left: obj setnum up: show-less down: show-less '\
'text: <f> menu menu </f> '\
'</o> '\
'<o> id: close select: show-less left: obj menu right: : up: show-less down: show-less '\
'text: <f> light-red x </f> '\
'</o>'
	make-render-area 6 7
	redraw
	obj close
}
function show-less {
	buffer[6]="${buffer[7]}"
	unset buffer[7]
	make-render-area 6 7
	redraw
	obj more
}

incnum=0

zero=(
	text: Menu
		face: menu-highlight
	text: Zero
		cmd: number-set 0
	text: One
		cmd: number-set 1
	text: Ten
		cmd: number-set 10
	text: Hundred
		cmd: number-set 100
	text: Thousand
		cmd: number-set 1000
	text: Million
		cmd: number-set 1000000
		face: menu-divider
	text: Close
		cmd: menu.exit
	text: Quit
		cmd: die
)
menu.add zero


function number-set {
	menu.exit
	incnum="$1"
	make-render-line 3
	redraw
}
	
buffer=(
''
'<lp> &line x/2-s/2 <h> Super number counter </h> </lp> <x> <lp> &line x/2-self_size[-2]/2 </lp>'
''
'<-> <f> highlight &bold-line <v> incnum &bold-line </f>'
''
# controls
'<o> id: inc select: inc redraw right: obj dec left: : up: : down: obj quit '\
'text: <f> link Increase </f> '\
'</o> '\
'<o> id: dec select: dec left: obj inc right: obj more up: : down: obj quit '\
'text: <f> link Decrease </f> '\
'</o> '\
'<o> id: more select: show-more left: obj dec right: : up: : down: obj quit '\
'text: <f> title ... </f> '\
'</o>'
# quit button
'<o> id: quit select: die right: : left: down: : up: obj inc text: <f> red Quit </f> </o>'
)

stty -echo
hooks[die]='stty echo'

load-default-config
init-var
#set-linenum
redraw
input-loop
